- packages/veritone-widgets-server/index.js
- packages/veritone-widgets-server/views/oauth_error.ejs
- packages/veritone-widgets/src/shared/VeritoneAuth.js
- Moved the singleton to the factory to remove a possible race condition
- Relaxed the cross-origin message event on the “gotOAuthToken?” to avoid a cross-origin error.
- Force a logout when clicking logging in when already logged in to better cleanup the state.
- Save the `authWindowListener` to better enforce the singleton.
> Cross-window message hardening

- packages/veritone-widgets/.babelrc
- packages/veritone-widgets/package.json
- packages/veritone-widgets/src/shared/VeritoneApp.js
- packages/veritone-widgets/webpack.config.js
babel-polyfill was causing an error when trying to use veritone-widgets in cms so I added babel-runtime and babel-plugin-transform-runtime and updated the webpack config to include the transform
> Addition of babel-runtime and babel-plugin-transform-runtime

- packages/veritone-react-common/src/components/SearchBar/story.js
- packages/veritone-react-common/src/components/SearchBar/styles.scss
- packages/veritone-react-common/src/components/SentimentSearchModal/index.js
- packages/veritone-react-common/src/components/SentimentSearchModal/index.test.js
- packages/veritone-react-common/src/components/SentimentSearchModal/story.js
NOTE: according to core-search-server tests, V3 query for sentiment should have a clause: select: ['text-recognition', 'veritone-job', 'veritone-file'];
This is probably not a business of this component to add this clause, unless I'm missing smth.
> Add Sentiment pill to search bar.

- packages/veritone-react-common/package.json
- packages/veritone-react-common/rollup.config.base.js
- packages/veritone-react-common/src/components/formComponents/RadioGroup.js
- packages/veritone-react-common/src/components/formComponents/Select.js
- packages/veritone-react-common/src/components/formComponents/TextField.js
- packages/veritone-react-common/src/components/formComponents/redux-form-material-ui.js
- yarn.lock
Redux-form-material-ui was causing build issues. I copied it into the SDK for now, so that we can hopefully go back to it seamlessly when the library is finally updated.
@charliemantle @gitrite
> VTN-6896:  remove redux-form-material-ui dependency

- packages/veritone-react-common/src/components/DataTable/index.js
- packages/veritone-react-common/src/components/DataTable/story.js
This PR
- Exposes the event object on table cell click. Adding this restores parity with cell click functionality in the developer-app table.
> Expose event on table cell click

- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/GeoPicker/index.js
- packages/veritone-react-common/src/components/GeoPicker/index.test.js
- packages/veritone-react-common/src/components/GeoPicker/story.js
- packages/veritone-react-common/src/components/GeoPicker/styles.scss
- packages/veritone-react-common/src/index.js
- yarn.lock
- Supports display a radius based distance, as well as a single geopoint. This will be used in contextMenus for the geopoint type, as well as the `Search by Geolocation` modal.
Ended up not using any of the React bindings because none of them are very good, they're kind of awkward since they end up storing a duplicate of Google map's internal state, meaning they have to write bindings for everything (some of which are missing and we need, see https://github.com/fullstackreact/google-maps-react/issues/171) 
Used https://github.com/Carrooi/Js-GoogleMapsLoader which is just an async loader.
Not sure if we need/how to test this either, since there's almost no React in this, all it is a declarative binding around Google Maps rendering a single marker or circle, and firing the callback when a …
> GeoPicker component to be used in both modals + static pages.

- packages/veritone-react-common/src/components/DelayedProgress/index.js
- packages/veritone-react-common/src/components/DelayedProgress/index.test.js
- packages/veritone-react-common/src/components/DelayedProgress/story.js
- packages/veritone-react-common/src/index.js
This wraps mui's CircularProgress with some logic to only appear after a certain delay, which is better from a UX perspective than immediately showing indicators for very short load times.
> add DelayedProgress component

- packages/veritone-react-common/src/components/FaceEngineOutput/EntityInformation/index.js
- packages/veritone-react-common/src/components/FingerprintEngineOutput/FingerprintEntity/EntityMetadata/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/faceEngineOutput/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/saga.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/transcriptWidget/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/transcriptWidget/saga.js
- packages/veritone-widgets/src/widgets/FaceEngineOutput/index.js
- packages/veritone-widgets/src/widgets/MediaDetails/index.js
- packages/veritone-widgets/src/widgets/TranscriptEngineOutputWidget/index.js
In certain scenarios when a user is editing a transcript or face engine output we need to warn them that their edits will be removed if they perform certain actions.
If the user has made edits and they hit the cancel or back button it should display a modal that asks them if they want to save their changes.
If they are in face or transcript and they change the engine id we need to warn them that their changes will be lost.
In transcript if they change the edit mode it should warn them that their changes will be lost.
> Sdo integration transcript/face save dialogs

- packages/veritone-widgets/src/redux/modules/engineSelection/index.js
- packages/veritone-widgets/src/widgets/EngineSelection/EngineListView/index.js
- packages/veritone-widgets/src/widgets/EngineSelection/index.js
Fixes issue where selected engines are not reinitialized across multiple widgets, and optimizes searchResults by hosting the tree outside of each widget.
> fix selected engines not initializing across widgets and hoist results

- packages/veritone-redux-common/src/helpers/api/index.js
- packages/veritone-redux-common/src/helpers/index.js
- packages/veritone-widgets/src/redux/modules/savedSearch/index.js
- packages/veritone-widgets/src/redux/rootReducer.js
When using multiple instances of veritone-sdk, the last one to be initiated is the redux store that gets used. So we need to move the saved-search to sdo-integration for now.
> Sdo integration saved search

- packages/veritone-react-common/src/components/BoundingPolyOverlay/Overlay.js
- packages/veritone-react-common/src/components/BoundingPolyOverlay/story.js
- packages/veritone-widgets/src/widgets/MediaPlayer/index.js
- packages/veritone-widgets/src/widgets/MediaPlayer/story.js
given a `overlayObjectType` in the bounding poly data structure, we can now apply styles to bounding boxes by type (and maybe future stuff, for example custom selection/editing behavior for different box types)
also removes mixBlendMode stuff in favor of simple rgba opacity since mixblend wasn't working in the video component. Can still be added in custom styles, just isn't first-class anymore.
> Bounding poly overlay styling

- packages/veritone-widgets/README.md
- packages/veritone-widgets/src/redux/modules/engineOutputExport/index.js
- packages/veritone-widgets/src/redux/modules/engineOutputExport/saga.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/EngineCategoryConfig.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/EngineCategoryConfigList.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/EngineConfigItem.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/SubtitleConfigForm.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/index.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/index.test.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/styles.scss
https://steel-ventures.atlassian.net/browse/VTN-9915
Changed how outputConfigurations are initialized. If there is more than one tdo object passed into the component then it is bulk export mode and we need to create only a single outputConfigurations object with an engine categoryId. This tells the API that the configuration can be applied to all engines ran on that tdo that fall under that engine category. If only a single tdo is passed in the tdo objects array then an outputConfigurations object needs to be created for each engine ran on that tdo and only include the engineId since the categoryId take precedence and the engineId will be ignored.
I also updated all the child components to reflect these changes.
This should not be a breaking change as it is all internal to the …
> VTN-9915 incorrect outputConfiguration for single tdo export

- packages/veritone-dev-env/.stylelintrc.js
disables `value-list-comma-newline-after` because it conflicts with prettier
> ignore stylelint rule that conflicts with prettier

- packages/veritone-widgets/src/widgets/MediaDetails/index.js
I removed the engineOutput export from behind the beta feature flag. The "Quick Export" menu item should now appear for all users in the more dropdown whether or not the bet flag is turned on.
@jordanheadley
> Remove the engineOutput export functionality from behind the beta flag.

- packages/veritone-widgets/src/widgets/MediaDetails/index.js
Reverts veritone/veritone-sdk#237
Shouldn't have merged this yet
> Revert "Remove the engineOutput export functionality from behind the beta flag."

- packages/veritone-widgets/src/redux/modules/mediaDetails/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/queries.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/saga.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-11610
Reviewers
---------
@ChrisPelletier @atb91590 
Purpose
-------
For Wazee integration when user edits entity in the face engine output, or resets edit to original - CMS should notify them.
What Changed
------------
In MDP added saga that'll call GQL to emit EntityUpdated even.
Decided to put that in MDP code because 1. potentially entities could be updated in different components: logo, object, face, etc. 2. This is Veritone+Wazee specific usecase, so probable smart components should not emit such event if reused outside of MDP.
How should we monitor this?
---------------------------
MDP save Face/Transcript, restore original should work as it worked before. For event check nsq logs on the environments.
Keep in mind that …
> VTN-11610 emit event when face entity is updated.

- packages/veritone-react-common/src/components/EngineOutputNullState/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/saga.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/index.test.js
- packages/veritone-widgets/src/widgets/MediaDetails/index.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-12260
There is a case in uk prod where temporalDataObject.details.veritoneFile has not been updated in the metadata yet. When we validate temporalDataObject.details.veritoneFile.mimetype against a the image regex it is undefined so the it assumes it is audio and video and displays a media player. I made a change to include contentType in the primary media asset of the tdo query and check that instead then use veritoneFile mimetype as a fallback. I also made a change to check if there is a primary media asset uri and if not display a null state image.
> VTN-12260 - image uploads displaying media player

- packages/veritone-widgets/src/redux/modules/mediaDetails/saga.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-11400
@ChrisPelletier 
If task is not in one of the final statuses for 24h+ consider it failed. Do this on the client. Api will respect task status.
GQL https://github.com/veritone/core-graphql-server/pull/1192
> VTN-11400 fail 24h+ incomplete tasks.

- packages/veritone-react-common/src/components/FaceEngineOutput/FaceInfoBox/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/FaceInfoBox/styles.scss
- packages/veritone-react-common/src/components/LibraryForm/index.test.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-11267
When filtering face detections for byScene view I realized that there was an issue where the media player was moving faster than media_streamer could return images. This lead to a performance issue where images that were no longer being displayed were still waiting for the requests to return the image. I added code that will cancel those requests if the component unmounts before the request can return an image.
> Optimize Image Loading

- packages/veritone-react-common/src/components/AppBar/index.js
- packages/veritone-react-common/src/components/AppBar/story.js
- packages/veritone-react-common/src/components/ProfileMenu/InnerProfileMenu.js
- packages/veritone-react-common/src/components/ProfileMenu/index.js
- packages/veritone-react-common/src/components/ProfileMenu/index.test.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-13096
> VTN-13096 App Configuration - Admin User Role

- packages/veritone-widgets/src/widgets/MediaDetails/index.js
https://steel-ventures.atlassian.net/browse/VTN-7652
Reviewer:
@atb91590 
What changed:
-------------
Remove `target="_blank"` to ignore open new tab when downloading the file from CMS.
> fix bug: VTN-7652-CMS-file-download-not-functioning-properly

- packages/veritone-widgets/src/shared/uploadFilesChannel.js
this change is needed for storage on azure blobs. adding this new header has no affect on our existing s3 use case.
It has been tested with both s3 buckets and azure blobs. Works perfectly fine.
After this merge has been made, we need to:
- increment widgets semvar
- publish this package to npm
- update all applications using veritone-widgets master (i'll take care of this part)
> account for azure uploads

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/FilePicker/FilePickerFooter/index.js
- packages/veritone-react-common/src/components/FilePicker/FilePickerHeader/FilePickerFlatHeader.js
- packages/veritone-react-common/src/components/FilePicker/FilePickerHeader/index.js
- packages/veritone-react-common/src/components/FilePicker/FilePickerHeader/styles.scss
- packages/veritone-react-common/src/components/FilePicker/FileUploader/index.js
- packages/veritone-react-common/src/components/FilePicker/FileUploader/styles.scss
- packages/veritone-react-common/src/components/FilePicker/index.js
- packages/veritone-react-common/src/components/FilePicker/story.js
- packages/veritone-react-common/src/components/FilePicker/styles.scss
* Added a non-modal style so it can sit flat in a modal, so we don’t have a modal on top of a modal
* Added maxFiles limit. When used, it shows {numberOfFilesToUpload} / {maxFiles}.
* Allow the upload button to be set via props, in case we want it to say “Benchmark” or “Process” as the next step instead.
* Better error messages when >1 file when multiple is false, better error messages when multiple is true, and maxFiles limit is set.
> Feature/VTN-20277 Non Modal File Picker

- packages/veritone-react-common/src/components/formComponents/DateTimePicker.js
- packages/veritone-react-common/src/components/formComponents/TimeRangePicker.js
- packages/veritone-react-common/src/components/formComponents/story.js
Pass timezone instead of showTimezone. We can override timezone this way. `true` could be passed for showing browser's default time zone.
> Pass timezone instead of showTimezone

- packages/veritone-react-common/src/components/AppBar/index.js
- packages/veritone-react-common/src/components/AppBar/styles.scss
- packages/veritone-react-common/src/components/ProfileMenu/index.js
- packages/veritone-react-common/src/components/ProfileMenu/styles.scss
https://steel-ventures.atlassian.net/browse/VTN-27962
I might have combined some of these into same commit;
Tool Tip hover on app switcher and user profile is too small. Should be 12px font size
Clicking the application name should always take you home
Using the application Switcher and selecting an application causes the user to be sent to the login screen
Edit Profile Button Color should be #0091EA
Increase Font Size of “Search Result” and “Watchlist” to 14
Remove Underline on Hover of “Search Result” and “ Watchlist”
Select Option of “Search Result” or “Watchlist” Should be #FFFFFF and unselected option should be Opacity 80%
Hover state of User profile background is offset and not centered to avatar
> feature/vtn-27962 Improve header bar

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
changes made were not documented and react-common was not incremented to 8.0.4
> Update changelog and increment ver for PR#403

- packages/veritone-widgets/src/widgets/DataPicker/index.js
-Fixed bug preventing internal redux state (required for widget mode) from conflicting with passing in open prop to DataPicker modal
-updated documentation inside component
> SDK/DataPicker: force open to use props.open if available

- packages/veritone-json-schemas/schemas/vtn-standard/concept/examples/include-text-indexing.json
https://steel-ventures.atlassian.net/browse/VTN-26012
In the "real world" content classification engines don't usually include
text indexing information for individual insights because they usually
cover the content classification for the document as a whole.
But it's fine if we continue supporting it, so I've moved it to a
secondary valid example.
(The "real world" example is used in our docs)
> VTN-26012 Remove text indexing from content classification real world example

- packages/veritone-functional-permissions/CHANGELOG.md
- packages/veritone-functional-permissions/package.json
https://steel-ventures.atlassian.net/browse/ES-910
* veritone-functional-permissions: upgrade jsonwebtoken to remove minimist vulnerabilities
> feature/ES-910 1523398 [Collections] Upgrade minimist

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/Help/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-37196
- Set anchorEl to null when user clicks openChatWindow()
- update CHANGELOG
- update veritone-react-common version to 10.0.5
@MmtBkn Once this PR has been approved and merged, could you please assist us with the deployment process for this fix? I would appreciate it! 
FYI @mikennedy16
> VTN-37196: Fix close help modal on Chat With Support click.

- packages/veritone-csp-generator/src/index.js
added following
1. query for sentiment search
2. make the sentiment score to be passed in. Default to positive 0.5 and negative 0.5 if no value passed in.
e.g. in onSearch function, add following:
csp.customizedSearch =  {
sentiment: {
positive: '0.6',
negative: '0.4'
}
}
let searchQuery = CSPToV3Query(csp);
> GLC-1687 generate query for sentiment search

- packages/veritone-json-schemas/schemas/vtn-standard/sentiment/examples/per-phrase.json
- packages/veritone-json-schemas/schemas/vtn-standard/sentiment/examples/polarized.negative.json
- packages/veritone-json-schemas/schemas/vtn-standard/sentiment/examples/polarized.positive.json
- packages/veritone-json-schemas/schemas/vtn-standard/sentiment/examples/simple-negative.json
veritione/aiware-core#492
Update examples to match documentation about sentiment representation in vtn-standard.
Also updated the page/paragraph/sentence values to be more realistic according to the docs
> vtn-standard: Clarify sentiment examples, remove polarization

- packages/veritone-react-common/src/components/MediaPlayer/VideoSource.js
- packages/veritone-react-common/src/index.js
Help is not currently exported from veritone-react-common SDK.
Fix lint warnings, as well.
> Export Help

- packages/veritone-react-common/src/components/MediaPlayer/VideoSource.js
**Link to ticket:**
https://veritone.atlassian.net/browse/MNE-3323
**Description:**
- Currently, if media has multi periods, the video will be stuck at the end of the first period. The solution is to add the `jumpLargeGaps` configuration which enables the video auto play the next period.
**How to test:**
- At the root folder, run `cd ./packages/veritone-react-common && yarn && yarn build`
- After the build is done, copy the folder `veritone-react-common` to `discovery-app/node_modules`
- Run the `discovery-app` with prod data ([How to use prod data locally](https://veritone.atlassian.net/wiki/spaces/~84864199/pages/3053814008/Cors+Bypass+cors+when+using+Prod+data+locally))
- Login to the app, use Org: Fox Women’s World Cup (46036) - user: …
> feat(MNE-3323): add jumpLargeGaps configuration into VideoSource

- packages/veritone-json-schemas/scripts/publish.sh
Oops, remove obsolete TODO comments
> Remove completed TODOs from publish script
