- packages/veritone-react-common/.gitignore
- packages/veritone-react-common/src/components/AppSwitcher/AppSwitcherItem.js
- packages/veritone-react-common/src/components/AppSwitcher/AppSwitcherList.js
- packages/veritone-react-common/src/components/AppSwitcher/index.js
- packages/veritone-react-common/src/components/AppSwitcher/index.test.js
- packages/veritone-react-common/src/components/formComponents/DateRangePicker.js
- packages/veritone-redux-common/package.json
- packages/veritone-redux-common/src/modules/user/index.js
- yarn.lock
* clean up appSwitcher, make it actually navigate to the selected app.
* tweak dateRangePicker to work better with redux-form and be smarter about min/max viewable dates (based on selectable range now, if provided)
* add a couple selectors to the user module related to fetching the current-user
> react-common/redux-common minor additions and features

- packages/veritone-react-common/src/components/RecognizedTextSearchModal/index.js
- packages/veritone-react-common/src/components/RecognizedTextSearchModal/index.test.js
- packages/veritone-react-common/src/components/RecognizedTextSearchModal/story.js
- packages/veritone-react-common/src/components/SearchBar/story.js
- packages/veritone-react-common/src/components/SearchBar/styles.scss
- packages/veritone-react-common/src/components/TranscriptSearchModal/index.js
1. Add Recognized Text pill component that does the exact text search.
2. Correct css to place pills in row - currently stacks in column
3. Change transcript modal text to be the same as in discovery-app
> Add ocr pill with query for exact text search

- packages/veritone-oauth-helpers/package.json
- packages/veritone-oauth-helpers/rollup.config.js
- yarn.lock
add CJS build to veritone-oauth-helpers
> Oauth helpers cjs

- packages/veritone-react-common/src/components/Form/index.js
- packages/veritone-react-common/src/components/Form/story.js
- packages/veritone-react-common/src/components/Form/styles.scss
> VTN-6922: Add datetime picker and select

- packages/veritone-dev-env/.eslintrc.react.js
- packages/veritone-react-common/src/components/DataTable/MenuColumn.js
- packages/veritone-react-common/src/components/DiscoverySideBar/SectionTree.js
- packages/veritone-react-common/src/components/FilePicker/FileList/index.js
- packages/veritone-widgets/src/widgets/Table/index.js
Tested and it threw like 20 warnings 😭
> Add `no-array-index-key` to `.eslint.react.js`

- packages/veritone-dev-env/.eslintrc.react.js
- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/DataTable/index.js
- packages/veritone-react-common/src/components/DataTable/shared.js
- packages/veritone-react-common/src/components/DataTable/table.test.js
- packages/veritone-react-common/src/components/DataTable/withBasicBehavior.js
- packages/veritone-react-common/src/index.js
- packages/veritone-redux-common/package.json
- packages/veritone-widgets/package.json
- yarn.lock
adding this one actually found a bug!
> add no-cycle eslint rule + fixes

- packages/veritone-react-common/src/components/DataTable/index.js
- packages/veritone-react-common/src/components/DataTable/table.test.js
This PR
- Adds support to enable table component to render nested data properties
> Added support in table for rendering nested properties in data prop

- packages/veritone-react-common/src/components/DataTable/index.js
- packages/veritone-react-common/src/components/DataTable/story.js
- packages/veritone-react-common/src/components/DataTable/table.test.js
- packages/veritone-react-common/src/components/IngestionJobs/IngestionJobTileView/index.js
- packages/veritone-react-common/src/components/IngestionJobs/story.js
- packages/veritone-widgets/src/widgets/IngestionJobsList/index.js
- packages/veritone-widgets/src/widgets/IngestionJobsList/story.js
This PR adds menu column to ingestion job list view
> Added menu column to ingestion job list view

- packages/veritone-react-common/src/styles/global.scss
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-7367
> VTN-7367: update Icon Version

- packages/veritone-react-common/src/styles/global.scss
https://steel-ventures.atlassian.net/browse/VTN-7383
> VTN-7383: update Icons to 20

- packages/veritone-client-js/apis/helper/callApi-base.js
- packages/veritone-client-js/apis/helper/callApi.spec.js
@JordanBelford @bgilkeyveritone fyi
> api client: loosen requirements on tokens to allow for unauthenticated API calls

- packages/veritone-react-common/src/components/Image/index.test.js
https://steel-ventures.atlassian.net/browse/VTN-8057
> add tests for image component

- packages/veritone-dev-env/package.json
- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/DataTable/withPagination.js
- packages/veritone-react-common/src/components/FilePicker/FileList/FileListItem.js
- packages/veritone-redux-common/src/components/withUIState/index.js
- packages/veritone-redux-common/src/components/withUIState/index.test.js
- packages/veritone-widgets/package.json
- yarn.lock
> add UNSAFE markers to methods to remove deprecation warnings

- packages/veritone-widgets/src/redux/modules/filePicker/filePickerSaga.js
- packages/veritone-widgets/src/redux/modules/notifications/index.js
- packages/veritone-widgets/src/redux/rootReducer.js
- packages/veritone-widgets/src/shared/BaseStory.js
- packages/veritone-widgets/src/widgets/Notifications/GlobalNotificationDialog.js
- packages/veritone-widgets/src/widgets/Notifications/GlobalSnackBar.js
- packages/veritone-widgets/src/widgets/Notifications/story.js
for showing shackbars and dialog notifications. Also fixed a small bug I found in the filepicker during testing and updated the BaseStory to work better in situations where only a widget or only a component is available.
> Bring in notifications module/components

- packages/veritone-react-common/src/components/StatusPill/index.test.js
@atb91590 
@olslash 
@charliemantle 
@gitrite
> VTN-8077: Add tests for StatusPill component

- packages/veritone-react-common/src/components/formComponents/DateTimePicker.js
- packages/veritone-react-common/src/components/formComponents/index.js
- packages/veritone-react-common/src/components/formComponents/story.js
- packages/veritone-react-common/src/components/formComponents/styles/dateTimePicker.scss
https://steel-ventures.atlassian.net/browse/VTN-8654
> Added 'DateTimePicker' component

- packages/veritone-react-common/src/components/ContentTemplates/index.js
- packages/veritone-widgets/src/widgets/ContentTemplate/index.js
- packages/veritone-widgets/src/widgets/ContentTemplate/story.js
- packages/veritone-widgets/src/widgets/ContentTemplateForm/story.js
- packages/veritone-widgets/src/widgets/SourceManagementForm/index.js
- packages/veritone-widgets/src/widgets/SourceManagementForm/story.js
- packages/veritone-widgets/src/widgets/SourceManagementOverview/index.js
- packages/veritone-widgets/src/widgets/SourceManagementOverview/story.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-7346
One thing that I've missed is updating widgets.
> Fix widgets that accept content templates to take an array.

- packages/veritone-react-common/src/components/AppBar/index.js
- packages/veritone-react-common/src/components/AppBar/story.js
- packages/veritone-redux-common/src/modules/user/index.js
- packages/veritone-widgets/src/widgets/AppBar/story.js
> AppBar: logout -> onLogout

- packages/veritone-redux-common/src/helpers/api/fetchGraphQLApi.js
- packages/veritone-redux-common/src/helpers/api/index.js
- packages/veritone-redux-common/src/modules/user/index.js
- packages/veritone-redux-common/src/modules/user/index.test.js
set credentials: 'include' for internal veritone apps using cookies, 'omit' for OAuth
> fix fetch credentials mode for redux-common api calls

- packages/veritone-react-common/src/components/SearchBar/FaceModal/index.js
- packages/veritone-react-common/src/components/SearchBar/FingerprintModal/index.js
- packages/veritone-react-common/src/components/SearchBar/GeolocationModal/index.js
- packages/veritone-react-common/src/components/SearchBar/LogoModal/index.js
- packages/veritone-react-common/src/components/SearchBar/OCRModal/index.js
- packages/veritone-react-common/src/components/SearchBar/ObjectModal/index.js
- packages/veritone-react-common/src/components/SearchBar/SentimentModal/index.js
- packages/veritone-react-common/src/components/SearchBar/StructuredDataModal/index.js
- packages/veritone-react-common/src/components/SearchBar/TagModal/index.js
- packages/veritone-react-common/src/components/SearchBar/TimeModal/index.js
- packages/veritone-react-common/src/components/SearchBar/TranscriptModal/index.js
- packages/veritone-react-common/src/components/SearchBar/engineCategoryMappings.js
- packages/veritone-react-common/src/components/SearchBar/index.js
- packages/veritone-react-common/src/components/SearchBar/index.test.js
- packages/veritone-react-common/src/components/SearchBar/story.js
- packages/veritone-react-common/src/components/SearchBar/styles.scss
- packages/veritone-react-common/src/components/SearchPill/styles.scss
- packages/veritone-react-common/src/components/formComponents/TimeRangePicker.js
- packages/veritone-react-common/src/components/formComponents/story.js
You can mostly ignore the time modal / structured data modals since the internal structure for the structured data modal will change, and the time modal should probably be updated as well.
> More engines

- packages/veritone-react-common/src/components/BoundingPolyOverlay/OverlayPositioningProvider.js
- packages/veritone-react-common/src/components/SourceManagement/SourceTileView/index.js
- packages/veritone-react-common/src/components/SourceManagement/SourceTileView/styles.scss
- packages/veritone-react-common/src/components/SourceManagement/story.js
- packages/veritone-react-common/src/components/share-components/Lightbox/index.js
- packages/veritone-react-common/src/components/share-components/Lightbox/index.test.js
- packages/veritone-react-common/src/components/share-components/Lightbox/story.js
- packages/veritone-react-common/src/components/share-components/Lightbox/styles.scss
- packages/veritone-react-common/src/components/share-components/buttons/ButtonWrapper/index.js
- packages/veritone-react-common/src/components/share-components/buttons/ButtonWrapper/index.test.js
- packages/veritone-react-common/src/index.js
- packages/veritone-widgets/src/build-entry.js
- packages/veritone-widgets/src/widgets/MediaPlayer/DefaultControlBar.js
- packages/veritone-widgets/src/widgets/MediaPlayer/Lightbox/MediaPlayerLightbox.js
- packages/veritone-widgets/src/widgets/MediaPlayer/Lightbox/index.js
- packages/veritone-widgets/src/widgets/MediaPlayer/Lightbox/index.test.js
- packages/veritone-widgets/src/widgets/MediaPlayer/Lightbox/styles.scss
- packages/veritone-widgets/src/widgets/MediaPlayer/index.js
- packages/veritone-widgets/src/widgets/MediaPlayer/story.js
- packages/veritone-widgets/src/widgets/SourceList/index.js
- packages/veritone-widgets/src/widgets/SourceList/story.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-8338
What Changed
------------
SourceList & SourceTileView to handle live stream status + button. 
Add MediaPlayerLightbox widget
> VTN-8338 Add RealTime UI

- publish-dev.sh
updated the vertione-widgets build script
> add dev build automation for veritone-widgets

- packages/veritone-redux-common/src/helpers/redux/fetchingStatus.js
- packages/veritone-redux-common/src/helpers/redux/handleApiCall.js
- packages/veritone-redux-common/src/helpers/redux/handleApiCall.test.js
- packages/veritone-redux-common/src/helpers/redux/index.js
- packages/veritone-redux-common/src/helpers/redux/index.test.js
- packages/veritone-redux-common/src/helpers/redux/paginate.js
- packages/veritone-redux-common/src/helpers/redux/paginate.test.js
- packages/veritone-redux-common/src/helpers/redux/reducer.js
- packages/veritone-redux-common/src/helpers/redux/reducer.test.js
> handleApiCall improvements

- packages/veritone-react-common/src/components/TranscriptEngineOutput/TranscriptContent/index.js
- packages/veritone-react-common/src/components/TranscriptEngineOutput/story.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-9810
Do not rely on API alone. Do this in UI too.
> UnEscape special characters in UI.

- packages/veritone-react-common/src/components/FaceEngineOutput/index.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-10261
Added counters to the Face Recognition and Detection tabs.
> VTN-10261 - Added counters to the face recognition and detection tabs

- packages/veritone-react-common/src/components/ProgramInfo/index.test.js
- packages/veritone-redux-common/src/modules/engineResults/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/faceEngineOutput/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/saga.js
- packages/veritone-widgets/src/widgets/FaceEngineOutput/index.js
- packages/veritone-widgets/src/widgets/MediaDetails/index.js
- packages/veritone-widgets/src/widgets/TranscriptEngineOutput/index.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-11113
Keep engine results mapped by tdoId.
> VTN-11113 keep engine results in redux store by tdoId - enables caching.

- packages/veritone-react-common/src/components/FaceEngineOutput/FaceDetectionBox/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/FaceDetectionBox/styles.scss
- packages/veritone-react-common/src/components/FaceEngineOutput/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/styles.scss
- packages/veritone-react-common/src/components/TranscriptEngineOutput/index.js
- packages/veritone-react-common/src/components/TranscriptEngineOutput/styles.scss
- packages/veritone-widgets/src/redux/modules/mediaDetails/faceEngineOutput/index.js
- packages/veritone-widgets/src/widgets/FaceEngineOutput/index.js
- packages/veritone-widgets/src/widgets/MediaDetails/Headers/EditHeader.js
- packages/veritone-widgets/src/widgets/MediaDetails/Headers/index.test.js
- packages/veritone-widgets/src/widgets/MediaDetails/Headers/styles.scss
- packages/veritone-widgets/src/widgets/MediaDetails/index.js
- packages/veritone-widgets/src/widgets/MediaDetails/styles.scss
- packages/veritone-widgets/src/widgets/TranscriptEngineOutput/index.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-10309
Moved the restore to original button/menu item from the more menu to the User-Edited/Original select dropdown.
> VTN-10309 reset to original uat changes

- packages/veritone-widgets/src/widgets/MediaDetails/index.js
Wrap over icon (dunno how this got lost).
> VTN-6539 more menu tooltip should not stick.

- packages/veritone-react-common/src/components/EngineOutputHeader/styles.scss
- packages/veritone-react-common/src/components/FaceEngineOutput/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/styles.scss
- packages/veritone-react-common/src/components/FingerprintEngineOutput/styles.scss
- packages/veritone-react-common/src/components/GeoEngineOutput/styles.scss
- packages/veritone-react-common/src/components/LogoDetectionEngineOutput/styles.scss
- packages/veritone-react-common/src/components/OCREngineOutputView/styles.scss
- packages/veritone-react-common/src/components/ObjectDetectionEngineOutput/styles.scss
- packages/veritone-react-common/src/components/SentimentEngineOutput/index.js
- packages/veritone-react-common/src/components/SentimentEngineOutput/styles.scss
- packages/veritone-react-common/src/components/StructuredDataEngineOutput/styles.scss
- packages/veritone-react-common/src/components/TranscriptEngineOutput/styles.scss
- packages/veritone-react-common/src/components/TranslationEngineOutput/styles.scss
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-11312
Moved the face tabs and hid the engine category name for face engine output when the user is in edit mode.
> VTN-11312 - Fixed where the face tabs appeared when in edit mode

- packages/veritone-react-common/src/components/ContentTemplates/ContentTemplateForm/index.js
- packages/veritone-react-common/src/components/ContentTemplates/TemplateForms/index.js
- packages/veritone-react-common/src/components/ContentTemplates/index.js
- packages/veritone-react-common/src/components/ContentTemplates/index.test.js
- packages/veritone-widgets/src/widgets/ContentTemplate/index.js
- packages/veritone-widgets/src/widgets/ContentTemplate/story.js
- packages/veritone-widgets/src/widgets/ContentTemplateForm/index.js
- packages/veritone-widgets/src/widgets/ContentTemplateForm/story.js
https://steel-ventures.atlassian.net/browse/VTN-11489
> Content template string type fields are now multiline

- packages/veritone-widgets/src/redux/modules/veritoneApp/index.js
- packages/veritone-widgets/src/redux/modules/veritoneApp/saga.js
- packages/veritone-widgets/src/redux/rootSaga.js
- packages/veritone-widgets/src/shared/VeritoneApp.js
- packages/veritone-widgets/src/shared/widget.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/index.js
- packages/veritone-widgets/src/widgets/EngineSelection/index.js
- packages/veritone-widgets/src/widgets/FilePicker/index.js
Reverts veritone/veritone-sdk#248
Not ready for prime time yet, it seems.
> Revert "dynamically run widget sagas"

- packages/veritone-functional-permissions/README.md
- packages/veritone-functional-permissions/permissions.js
- packages/veritone-functional-permissions/permissions_json.go
Task: https://steel-ventures.atlassian.net/browse/VTN-11704
Changes:
- Update README with missing function docs.
- Update permissions with latest from https://github.com/veritone/functional-permissions-lib
** Note: Supersedes PR https://github.com/veritone/veritone-sdk/pull/272 **
> Add latest from functional-permissions-lib

- packages/veritone-react-common/src/components/EngineOutputNullState/index.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-11400
Reviewers
---------
@ChrisPelletier @jordanheadley 
Purpose
-------
Add 'aborted' status. Hadcode less. 
What Changed
------------
Added new status.
> VTN-11400 support 'aborted' engine status, plus less hardcoded statuses

- packages/veritone-react-common/src/components/EngineOutputNullState/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/FacesByFrame/styles.scss
- packages/veritone-react-common/src/components/FaceEngineOutput/FacesByScene/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/RecognizedFaceMatch/index.js
- packages/veritone-react-common/src/components/FaceEngineOutput/index.js
- packages/veritone-widgets/src/redux/modules/mediaDetails/faceEngineOutput/index.js
- packages/veritone-widgets/src/widgets/FaceEngineOutput/index.js
https://steel-ventures.atlassian.net/projects/VTN/issues/VTN-11620
When we are displaying face detection and the users select By Scene in the engine output header dropdown we should be filtering both face detections and face recognitions.
> By Scene face detection filtering

- packages/veritone-react-common/package.json
- packages/veritone-react-common/src/components/CopyPrompt/index.js
- packages/veritone-react-common/src/components/CopyPrompt/story.js
- packages/veritone-react-common/src/components/CopyPrompt/styles.scss
- yarn.lock
> migrate CopyPrompt from developer app

- packages/veritone-react-common/src/components/ContentTemplates/index.js
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-133276
Reviewers
@atb91590 
What Changed
add data-veritone-component for MDP content template page
> add data-veritone-component for MDP content template page

- packages/veritone-react-common/src/components/SentimentEngineOutput/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-14152
Reviewer:
@atb91590
What's changed:
Fix Sentiment Graph in MDP does not display
> VTN-14152-Fix-Sentiment-Graph-in-MDP-does-not-display

- packages/veritone-react-common/src/components/SearchBar/SearchBarContainer.js
- packages/veritone-react-common/src/components/SearchBar/component.js
https://steel-ventures.atlassian.net/browse/VTN-18125
> set defaultJoinOperator on higher level

- packages/veritone-react-common/src/components/SearchBar/SearchBarContainer.js
- packages/veritone-react-common/src/components/SearchBar/component.js
https://steel-ventures.atlassian.net/browse/VTN-18110
> tag category search title w/ data-veritone-element so pendo can track it

- packages/veritone-react-common/src/components/LogoDetectionEngineOutput/styles.scss
- packages/veritone-react-common/src/components/OCREngineOutputView/styles.scss
- packages/veritone-react-common/src/components/ObjectDetectionEngineOutput/styles.scss
- packages/veritone-react-common/src/components/TranscriptEngineOutput/styles.scss
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-19465
Reviewers
@atb91590
Purpose
Fix bug VTN-19465
> VTN-19465: Can't scroll down page to see more result in MDP Text Recognition

- packages/veritone-react-common/src/components/AppSwitcher/index.js
- packages/veritone-react-common/src/components/ProfileMenu/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-18744
Purpose: add some pendo tagging
> ticket-VTN-18744 add pendo tagging

- packages/veritone-widgets/src/widgets/MediaDetails/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-19650
Purpose:
----------
Fix bug VTN-19650:Audio_Fingerprinting_Engine_Time_stamp_links_dont_work_in_CMS
Reviewer:
---------
@atb91590 
@seta-tuha
> VTN-19650:Audio_Fingerprinting_Engine_Time_stamp_links_dont_work_in_CMS

- packages/veritone-react-common/src/components/FilePicker/FileList/styles.scss
Link to ticket https://steel-ventures.atlassian.net/browse/VTN-21354
Link to ticket https://steel-ventures.atlassian.net/browse/VTN-21353
Reviewer
@atb91590
Purpose
Fix bug: VTN-21354 and VTN-21353
> VTN-21354:move-scroll-inside-the-image-list

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-widgets/CHANGELOG.md
- packages/veritone-widgets/package.json
> inc semver and add changelogs

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-widgets/CHANGELOG.md
- packages/veritone-widgets/package.json
https://steel-ventures.atlassian.net/browse/VTN-24054
https://steel-ventures.atlassian.net/browse/VTN-24770
publish notification component
> VTN-24054 prepare to publish Notification component

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-widgets/CHANGELOG.md
- packages/veritone-widgets/package.json
Story: https://steel-ventures.atlassian.net/browse/VTN-24054
Standardize Header Bar.
Changes:
• Add Help Component
1. Add a button to open help doc
2. Add a button to open **Chat With Support** window
• Add Pendo Tag to Notifier & Help components
• Update Styling on Notifier & User Profile components
• Add Tooltips to Notifier, App Switcher & User Profile Component
> VTN-24054 add changelogs for standardize AppBar & Help component

- packages/veritone-react-common/src/components/AppBar/styles.scss
- packages/veritone-react-common/src/components/Notifier/index.js
https://steel-ventures.atlassian.net/browse/VTN-26756
> change .logo to nested class

- packages/veritone-functional-permissions/permissions.js
- packages/veritone-functional-permissions/permissions_json.go
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-26901
Reviewer:
@jialu98 
Purpose:
copy latest permissions from veritone/functional-permissions-lib
> Copy illuminate.access from latest veritone/functional-permissions-lib

- packages/veritone-functional-permissions/permissions.js
- packages/veritone-functional-permissions/permissions_json.go
Link to Ticket: https://steel-ventures.atlassian.net/browse/VTN-26901
Reviewers
@steveshaffer
@jialu98 
Purpose
Revert Illuminate new permission for later release
> Revert illuminate new permission

- packages/veritone-widgets/src/widgets/EngineOutputExport/EngineConfigItem.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/styles.scss
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-11030
Purpose:
Add hint text to dropdown on export page
What changed:
EngineConfigItem.js : update code and styles
> VTN-11030: Add hint text to dropdown on export page

- packages/veritone-widgets/src/redux/configureStore.js
https://steel-ventures.atlassian.net/browse/VTN-28264
> VTN-28264 [STAGE] [FILE PICKER] Uploading duplicate file / Remove unnecessary code (partially reverts ece2965421457ce99c3d40f450dd2c6df5e0e8f6)

- packages/veritone-csp-generator/src/index.js
Link to ticket: 
https://steel-ventures.atlassian.net/browse/VTN-27026
Purpose: 
Change the value of Sunday in search param from "7" to "0".
> VTN-27026-search-by-time-station-local-time-toggle-not-working

- packages/veritone-react-common/src/components/NavigationSideBar/SectionTree.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-28853
Purpose:
--------------------
Add data-veritone-element for sidebar to support tracking by pendo
> VTN-28853: Add data-veritone-element for sidebar

- packages/veritone-csp-generator/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-25072
Purposed:
Update the CSP generator with advanced search options
What's changed:
Object and logo generator.
> VTN-25072-search_bar_upgrade_csp_generator

- packages/veritone-redux-common/src/helpers/api/callGraphQLApi.js
Added response to meta for callGraphQLApi to access raw response even during error type dispatches
> Added response to meta for callGraphQLApi to access raw response

- packages/veritone-react-common/src/components/SearchBar/SearchBarContainer.js
- packages/veritone-react-common/src/components/SearchBar/component.js
https://steel-ventures.atlassian.net/browse/VTN-29346
https://steel-ventures.atlassian.net/browse/VTN-29583
Purpose: 
update the searchbar follow the ticket
> Update after reviewing and add editer permission

- packages/veritone-react-common/src/components/SearchBar/component.js
> Delete unused code

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
Included breaking issues with mui/react upgrades, reverting.
> Revert pull request #419 and remove v8.0.4 for react-common

- packages/veritone-react-common/src/components/FormBuilder/Form.story.js
- packages/veritone-react-common/src/components/FormBuilder/helpers.js
- packages/veritone-react-common/src/components/FormBuilder/helpers.test.js
- packages/veritone-react-common/src/components/FormBuilder/utils.js
- packages/veritone-react-common/src/components/FormBuilder/utils.test.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-29400
> Update form utils

- packages/veritone-react-common/src/components/AdvancedPanel/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/VTN-30571
> VTN-30571: Remove info link on advanced search

- packages/veritone-widgets/src/widgets/DataPicker/index.js
1. Exposed open prop for data picker and fall back on prop state for using .pick() function
2. Default DataPicker to modal mode and exposed MUI Dialog fullWidth prop
> Exposed open prop for DataPicker

- packages/veritone-react-common/src/components/ProfileMenu/index.js
Menu Component took over the focus.
> VTN-32129: fix input edit of user profile is missed focus

- packages/veritone-widgets/src/redux/modules/folder/index.js
- packages/veritone-widgets/src/widgets/FolderTree/index.js
https://steel-ventures.atlassian.net/browse/ES-116
> ES-117: Change Collection Label

- packages/veritone-react-common/src/components/FolderTree/Modals/EditFolder/index.js
- packages/veritone-react-common/src/components/FolderTree/Modals/EditFolder/story.js
- packages/veritone-react-common/src/components/FolderTree/Modals/EditFolder/styles.js
link to ticket:
https://steel-ventures.atlassian.net/browse/ES-121
https://steel-ventures.atlassian.net/browse/ES-131
> ES-121: Change width of Edit Folder Name

- packages/veritone-widgets/src/widgets/EngineOutputExport/EngineConfigItem.js
- packages/veritone-widgets/src/widgets/EngineOutputExport/styles.js
Link to ticket
https://steel-ventures.atlassian.net/browse/ES-429
> ES-429 -  Export format form should be displayed on a par with engine name

- packages/veritone-react-common/src/components/AppBar/styles.js
Link to ticket: https://steel-ventures.atlassian.net/browse/ES-417
> ES-417: show hand icon when hovering watchlist and search results

- packages/veritone-react-common/src/components/AppBar/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/ES-306
> ES-306: redirect back landing page once clicking on the logo

- packages/veritone-widgets/src/widgets/MediaPlayer/styles.js
Link to ticket: 
https://steel-ventures.atlassian.net/browse/ES-425
> ES-425: update player control bar style

- packages/veritone-widgets/src/widgets/UserProfile/index.js
https://steel-ventures.atlassian.net/browse/GLC-344
> GLC-344: Fix ForwardRef Modal warning

- packages/veritone-react-common/src/components/formComponents/DateTimePicker.js
https://steel-ventures.atlassian.net/browse/ES-512
https://steel-ventures.atlassian.net/browse/ES-513
> ES-512: fix date-fns error in form components

- packages/veritone-widgets/src/redux/modules/folder/sagas/createFolderSagas.js
- packages/veritone-widgets/src/redux/modules/folder/sagas/deleteFolderSaga.js
- packages/veritone-widgets/src/redux/modules/folder/sagas/editFolderSaga.js
https://steel-ventures.atlassian.net/browse/ES-550
> ES-550: add notification when api error

- packages/veritone-widgets/src/redux/modules/folder/reducer.js
- packages/veritone-widgets/src/redux/modules/folder/sagas/deleteFolderSaga.js
https://steel-ventures.atlassian.net/browse/ES-610
> ES-610: Collection still exists when its folder is deleted

- packages/veritone-widgets/src/redux/modules/folder/sagas/deleteFolderSaga.js
https://steel-ventures.atlassian.net/browse/ES-610
Update selected logic when deleting the parent folder
> ES-610: update-selected-logic-when-delete-folder

- packages/veritone-react-common/src/components/AppBar/index.js
- packages/veritone-react-common/src/components/FolderTree/Searchbox/index.js
- packages/veritone-widgets/src/widgets/FolderTree/index.js
Jira ticket:
https://steel-ventures.atlassian.net/browse/ES-813
> Add data test Foldertree widget and appbar

- packages/veritone-widgets/package.json
- packages/veritone-widgets/src/widgets/UserProfile/PasswordField/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/ES-677
> ES-677 Fix Year is not displayed in account last updated password

- packages/veritone-react-common/src/components/FolderTree/Modals/CreateFolder/index.js
- packages/veritone-react-common/src/components/FolderTree/Modals/EditFolder/index.js
Link to ticket [ES-871](https://steel-ventures.atlassian.net/browse/ES-871)
> ES-871 [Collections] Folder/Collection name can contain ONLY space

- packages/veritone-csp-generator/CHANGELOG.md
- packages/veritone-csp-generator/package.json
- packages/veritone-csp-generator/src/index.js
- yarn.lock
csp-generator used to live in search_bar branch, we like to move it to master and make future relases from master
> Move csp-generator to master branch

- packages/veritone-client-js/CHANGELOG.md
- packages/veritone-client-js/package.json
https://steel-ventures.atlassian.net/browse/ES-915
> ES-915 1523410 [Collections] Upgrade axios (see package-lock file)

- packages/veritone-functional-permissions/package.json
https://steel-ventures.atlassian.net/browse/ES-910
* veritone-functional-permissions semver number 1.0.2 was already published to npm
* upgrade to 1.0.3 to release
> feature/ES-910 1523398 [Collections] Upgrade minimist

- packages/veritone-redux-common/CHANGELOG.md
- packages/veritone-redux-common/package.json
https://steel-ventures.atlassian.net/browse/ES-899
veritone-redux-common changes:
* upgrade package veritone-functional-permissions
* update changelog
* update semver number to 3.11.8
> feature/ES-899 1523416 [Collections] Upgrade hoek

- packages/veritone-csp-generator/CHANGELOG.md
- packages/veritone-csp-generator/package.json
- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
- packages/veritone-redux-common/CHANGELOG.md
- packages/veritone-redux-common/package.json
- packages/veritone-widgets/CHANGELOG.md
- packages/veritone-widgets/package.json
Updates versions, and changelogs
> Release latest changes

- packages/veritone-json-schemas/CHANGELOG.md
- packages/veritone-json-schemas/README.md
- packages/veritone-json-schemas/package.json
- packages/veritone-json-schemas/src/index.js
Prepare release of veritone-json-schema 1.2.0
> Feature/release schema 1.2.0

- packages/veritone-react-common/src/components/MediaPlayer/VideoSource.js
- packages/veritone-react-common/src/components/MediaPlayer/index.js
Link to ticket: https://steel-ventures.atlassian.net/browse/GLC-3817
> Feature/GLC-3817-Illuminate - Indiana State Police transcript timing out after 3 hours

- packages/veritone-react-common/CHANGELOG.md
- packages/veritone-react-common/package.json
Update `vertione-react-common` to 10.0.8.
> release veritone-react-common v10.0.8

- packages/veritone-csp-generator/src/index.js
Link to ticket: https://veritone.atlassian.net/browse/VE-3151
> VE-3151-[Illuminate][Search file] Search by face and sentiment issue
